# Jarvis Packages

# Package
[package]
name = "jarvis_package_template"
display-name = "jPackage-Template"
version = "1.0.0"
jarvis-version = "0.0.2" # Jarvis version
description = "A Template file for Jarvis Package"
authors = ["Jarvis-Packages"]
repository = ""
